name: Build SIFT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y \
          cmake \
          build-essential \
          libgtest-dev
    - name: Configure CMake
      run: |
        cmake -B build -S . -DSIFT_USE_OPENCV=OFF -DBUILD_TESTING=ON
    - name: Build project
      run: |
        cmake --build build --config Release
    - name: List tests
      run: |
        ctest --test-dir build -N
    - name: Run tests
      run: |
        ctest --test-dir build --output-on-failure
    - name: Run GoogleTest directly
      run: |
        ./build/sift/tests/test_gaussian --gtest_list_tests
        ./build/sift/tests/test_gaussian_pyramid --gtest_list_tests

